In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler

### Informasi dataset

In [12]:
df = sns.load_dataset('titanic')
df.head(5)
# df.info()
# df.describe()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### Menangani nilai hilang (missing value)

In [13]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [14]:
# menghapus kolom deck karena memiliki banyak nilai null
df = df.drop('deck', axis=1)
# mengisi nilai null pada kolom age dengan median
df['age'] = df['age'].fillna(df['age'].median())
# mengisi nilai null pada kolom embarked dengan modus
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

### Menangani data duplikat

In [15]:
print(f'Baris duplikat : {df.duplicated().sum()}')

Baris duplikat : 116

In [16]:
df = df.drop_duplicates()
print(f'Baris duplikat : {df.duplicated().sum()}')
print(f'Jumlah baris setelah menghapus duplikat : {len(df)}')

Baris duplikat : 0
Jumlah baris setelah menghapus duplikat : 775

### Validasi dan konversi tipe data

In [17]:
df.info()

# Konversi survived menjadi tipe data boolean
df['survived'] = df['survived'].astype(bool)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 775 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     775 non-null    int64
 1   pclass       775 non-null    int64
 2   sex          775 non-null    object
 3   age          775 non-null    float64
 4   sibsp        775 non-null    int64
 5   parch        775 non-null    int64
 6   fare         775 non-null    float64
 7   embarked     775 non-null    object
 8   class        775 non-null    category
 9   who          775 non-null    object
 10  adult_male   775 non-null    bool
 11  embark_town  775 non-null    object
 12  alive        775 non-null    object
 13  alone        775 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 75.1+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 775 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     775 non-null    bool
 1   pclass       775 non-null    int64
 2   sex          775 non-null    object
 3   age          775 non-null    float64
 4   sibsp        775 non-null    int64
 5   parch        775 non-null    int64
 6   fare         775 non-null    float64
 7   embarked     775 non-null    object
 8   class        775 non-null    category
 9   who          775 non-null    object
 10  adult_male   775 non-null    bool
 11  embark_town  775 non-null    object
 12  alive        775 non-null    object
 13  alone        775 non-null    bool
dtypes: bool(3), category(1), float64(2), int64(3), object(5)
memory usage: 69.8+ KB

### Sclaing numerik (normalisasi dan standarisasi)

In [18]:
scaler = MinMaxScaler()
df['fare_normalized'] = scaler.fit_transform(df[['fare']])
print("Normalisasi dengan MinMaxScaler:")
df[['fare', 'fare_normalized']].head()

Normalisasi dengan MinMaxScaler:

      fare  fare_normalized
0   7.2500         0.014151
1  71.2833         0.139136
2   7.9250         0.015469
3  53.1000         0.103644
4   8.0500         0.015713

In [19]:
scaler = StandardScaler()
df['fare_standardized'] = scaler.fit_transform(df[['fare']])
print("Standardisasi dengan StandardScaler:")
df[['fare', 'fare_standardized']].head()

Standardisasi dengan StandardScaler:

      fare  fare_standardized
0   7.2500          -0.527515
1  71.2833           0.695086
2   7.9250          -0.514627
3  53.1000           0.347909
4   8.0500          -0.512240

### Menyimpan data bersih

In [20]:
df.to_csv('titanic_cleaned.csv', index=False)